### ISSUE TITLE
The Integration always shows as offline is GOG Galaxy 2.0

### ISSUE THREAD

**Issue by egImmortal** [FriendsOfGalaxy/galaxy-integration-psn#38]
**Describe the bug**
The Integration always shows as offline is GOG Galaxy 2.0

**To Reproduce**
1 . Login with your account to the psn integration

**Expected behavior**
It will load for 20 secs and say that it is offline.

**Attached logs**
[plugin-psn-38087aea-3c30-439f-867d-ddf9fae8fe6f.log](https://github.com/FriendsOfGalaxy/galaxy-integration-psn/files/7502117/plugin-psn-38087aea-3c30-439f-867d-ddf9fae8fe6f.log)

**Comment by egImmortal** [comment]
btw sorry for doing the bug report properly the first time.

**Comment by FriendsOfGalaxy** [comment]
Hi, thanks for the report. I have no reproduction, but from your logs, seems clearly that something goes very wrong.

the code is
```python
    async def get(self, url, *args, **kwargs):
        silent = kwargs.pop('silent', False)
        get_json = kwargs.pop('get_json', True)
        response = await self._request("GET", *args, url=url, **kwargs)
        try:
            raw_response = '***' if silent else await response.text()
            logging.debug("Response for:\n{url}\n{data}".format(url=url, data=raw_response))
            return await response.json() if get_json else await response.text()
        except ValueError:
            logging.exception("Invalid response data for:\n{url}".format(url=url))
            raise UnknownBackendResponse()
```

I have no idea how it is possible that response is `None`. According to aiohttp session request always returns `Response` object.

```
Traceback (most recent call last):
  File "C:\Users\immortal\AppData\Local\GOG.com\Galaxy\plugins\installed\psn_38087aea-3c30-439f-867d-ddf9fae8fe6f\galaxy\api\jsonrpc.py", line 271, in handle
    result = await callback(*bound_args.args, **bound_args.kwargs)
  File "C:\Users\immortal\AppData\Local\GOG.com\Galaxy\plugins\installed\psn_38087aea-3c30-439f-867d-ddf9fae8fe6f\galaxy\api\plugin.py", line 252, in method
    result = await handler_(*args, **kwargs)
  File "C:\Users\immortal\AppData\Local\GOG.com\Galaxy\plugins\installed\psn_38087aea-3c30-439f-867d-ddf9fae8fe6f\galaxy\api\plugin.py", line 264, in wrapper
    return await self._external_task_manager.create_task(handler(*args, **kwargs), name, False)
  File "C:\Users\immortal\AppData\Local\GOG.com\Galaxy\plugins\installed\psn_38087aea-3c30-439f-867d-ddf9fae8fe6f\galaxy\task_manager.py", line 21, in task_wrapper
    result = await coro
  File "C:\Users\immortal\AppData\Local\GOG.com\Galaxy\plugins\installed\psn_38087aea-3c30-439f-867d-ddf9fae8fe6f\plugin.py", line 59, in pass_login_credentials
    return await self._do_auth(cookies)
  File "C:\Users\immortal\AppData\Local\GOG.com\Galaxy\plugins\installed\psn_38087aea-3c30-439f-867d-ddf9fae8fe6f\plugin.py", line 42, in _do_auth
    await self._http_client.refresh_cookies()
  File "C:\Users\immortal\AppData\Local\GOG.com\Galaxy\plugins\installed\psn_38087aea-3c30-439f-867d-ddf9fae8fe6f\http_client.py", line 74, in refresh_cookies
    await self.get(REFRESH_COOKIES_URL, silent=True, get_json=False)
  File "C:\Users\immortal\AppData\Local\GOG.com\Galaxy\plugins\installed\psn_38087aea-3c30-439f-867d-ddf9fae8fe6f\http_client.py", line 56, in get
    return await response.json() if get_json else await response.text()
AttributeError: 'NoneType' object has no attribute 'text
```

**Comment by egImmortal** [comment]
do I delete the plugin files and install them again?

**Comment by egImmortal** [comment]
so i just did that and the same thing happens again so umm i will uninstall gog galaxy 2.0 and try again

**Comment by egImmortal** [comment]
so I did the same thing on a fresh install and it still gives me the same output anyway here's the log files in case anything changed because of the new insta
[plugin-psn-38087aea-3c30-439f-867d-ddf9fae8fe6f.log](https://github.com/FriendsOfGalaxy/galaxy-integration-psn/files/7604187/plugin-psn-38087aea-3c30-439f-867d-ddf9fae8fe6f.log)
ll

**Comment by egImmortal** [comment]
if you want me to do anything , just tell me what it is and i will try to do it

**Comment by FriendsOfGalaxy** [comment]
Hi, I'm sorry to hear that restarting didn't help. It is probably related to your account. Have you accepted all the eulas when logging into psn in browser? (just guessing)

I can't work anymore for this integration, but if someone else want to dig into the issue I would extend logging to check what is wrong with this method and `response`. Maybe a bug in aiohttp or maybe we do something stupid.
